//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Decimal(Some((16, 2)))", nullable)]
    pub amount: Option<Decimal>,
    pub self_account: String,
    pub trading_time: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub classification_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::classification::Entity",
        from = "Column::ClassificationId",
        to = "super::classification::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Classification,
}

impl Related<super::classification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classification.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
